### ISSUE TITLE
Response/Request properties that are objects don't render properly if one of their properties is also an object.

### ISSUE THREAD

**Issue by boralyl** [upsight/doctor#9]
With a schema for this definition that looks something like:

```yaml
push_campaign_snapshot:
    description: >
      A snapshot of the Push Campaign when it was triggered.
    type: object
    properties:
      created_on:
        $ref: 'push_campaign.yaml#/definitions/created_on'
      scheduling:
        $ref: 'push_campaign.yaml#/definitions/scheduling'
```

Where scheduling is also an object it closes the ul rather than embedding another one:

![](https://s3.amazonaws.com/uploads.hipchat.com/92542/678236/CkxOY2tobaxTOfk/upload.png)

Scheduling should be indented another level, but is not:

![](https://s3.amazonaws.com/uploads.hipchat.com/92542/678236/yTldCKVlg53Qk7O/upload.png)
